# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Heroku Deployment

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:

  deploy:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo v2
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
        
      - name: Deploying to Heroku
        env:
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
          APP: ${{ secrets.HEROKU_APP }}
        run: |
          git remote add heroku https://heroku:$TOKEN@git.heroku.com/$APP.git
          git push heroku HEAD:master -f
