# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Webapp CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:

  installation:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo v2
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Running Build
        run: npm build
  
  deploy:
    
    runs-on: ubuntu-latest
    
    needs: [installation]

    steps:
      - name: Checkout Repo v2
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
        
      - name: Deploying to Heroku
        run: sh deploy.sh
